name: Main Taski Workflow
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkkkkking our staff
        uses: actions/checkout@v3
      - name: Python INSTALL
        uses: actions/setup-python@v4
        with: 
          python-version: 3.12
      - name: INSTALL DePeNdEnCeS
        run: |
          python -m pip install --upgrade pip setuptools
          pip install flake8==6.0.0 flake8-isort==6.0.0
      - name: HERE WE GO TESTING (flake8)
        run: pythom -m flake8 backend/